server:
  port: 80

spring:
  datasource:
    url: jdbc:mysql://47.92.101.125:3306/spring-boot?serverTimezone=GMT%2B8
    username: root
    password: 216084lI.
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    check-template: false
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.autumn.weather.entity
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
